Disable touch on nodes w/o children
zaguiini/react-native-final-tree-view pull request #13
Opened 2020-04-14 09:56 UTC by brightsider

2020-04-14 10:30 UTC, zaguiini commented
Thanks for your contribution!

I'm not sure if I agree with it, though. Why are we disabling the touch of the node? The user might have a callback on node touch and we're explicitly disabling it... What's the motivation behind your PR?

2020-04-14 10:54 UTC, brightsider commented
I don't need a touch animation when don't have children. I can add options to control this

2020-04-14 10:55 UTC, zaguiini commented
So isn't it better to add a prop like `disableTouchOnLeaves`?

2020-04-14 11:00 UTC, brightsider commented
`disableTouchOnLeaves` should be a function or a boolean?

2020-04-14 11:03 UTC, zaguiini commented
A function. A better name for it would be `shouldDisableTouchOnLeaf(node)` I think. WDYT?

2020-04-14 11:29 UTC, brightsider commented
It's looks better? :)

2020-04-14 12:29 UTC, zaguiini requested changes

2020-04-14 12:29 UTC, zaguiini commented on index.js
> +              [this.props.idKey]: node[this.props.idKey],
You should pass only `node` here

2020-04-15 10:02 UTC, merged

2020-04-15 10:02 UTC, zaguiini commented
Thanks!

2020-04-15 10:05 UTC, zaguiini commented
Shipped on `v2.0.3`.